<?php
/**
 * Implements hook_block_info().
 */
function annuaire_login_block_info() {
  $blocks = array();

  $blocks['annuaire_login'] = array(
    'info' => t('Annuiare user login'), 
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function annuaire_login_block_view($delta = '') {
  $block = array();

  $block['subject'] = t('');
  $block['content'] = drupal_get_form('annuaire_login_form');

  return $block;
}

/**
 * Custom form.
 */
function annuaire_login_form($form, &$form_state) {
  
  $form['username'] = array(
    '#type' => 'textfield',
    '#title' => t('username'),
    '#attributes' => array('Placeholder' => 'Utilisateur', 'Class' => 'input'),
  );

  $form['password'] = array(
    '#type' => 'password',
    '#title' => t('Mot de passe'),
    '#attributes' => array('placeholder' => 'Mot de passe', 'Class' => 'input'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('ok'),
  );

  $form['#suffix'] = '<div id="annlink" class="block"><a href="#" class="passoublie" titre="Mot de passe oublie ?">Mot de passe oublie ?</a><a href="#" class="modpass" titre="Modifier votre mot de passe">Modifier votre mot de passe</a></div>';

  return $form;
}

/**
 * Custom form submit function.
 */
function annuaire_login_form_submit($form, &$form_state) {
  // You need the have Devel module enabled for dpm() to work.
  //dpm($form_state);
}